--- WW3/model/esmf/Makefile	2019-10-10 13:52:45.000000000 -0500
+++ WW3/model/esmf/Makefile	2020-12-09 22:34:09.821283926 -0600
@@ -3,16 +3,20 @@
 ################################################################################
 
 WW3_DIR  := $(shell cd .. 1>/dev/null 2>&1 && pwd)
+WW3_BASEDIR  := $(shell cd ../.. 1>/dev/null 2>&1 && pwd)
 WW3_BINDIR := $(WW3_DIR)/bin
 WW3_TMPDIR := $(WW3_DIR)/tmp
 WW3_EXEDIR := $(WW3_DIR)/exe
+COMP_BINDIR ?= $(WW3_BASEDIR)/exe
 WW3_COMP ?= gnu
 WW3_CC := gcc
 WW3_F90 := gfortran
 SWITCHES := $(shell cat switch)
 
 WWATCH3_ENV := $(WW3_BINDIR)/wwatch3.env
-export WWATCH3_ENV
+WWATCH3_NETCDF := NC4
+NETCDF_CONFIG := $(shell which nc-config)
+export WWATCH3_ENV WWATCH3_NETCDF NETCDF_CONFIG
 
 EXE := $(WW3_EXEDIR)/ww3_multi_esmf
 
@@ -154,25 +158,22 @@
 gout: 
 	@echo "$(SWITCHES)" > $(WW3_BINDIR)/tempswitch
 	@sed -e "s/DIST/SHRD/g"\
+	     -e "s/OMPG/ /g"\
+	     -e "s/OMPH/ /g"\
 	     -e "s/MPIT/ /g"\
-             -e "s/MPI/ /g"\
-             -e "s/PDLIB/ /g"\
-                  $(WW3_BINDIR)/tempswitch > $(WW3_BINDIR)/switch
+	     -e "s/MPI/ /g"\
+	     -e "s/PDLIB/ /g"\
+	          $(WW3_BINDIR)/tempswitch > $(WW3_BINDIR)/switch
 	\rm -f $(WW3_BINDIR)/tempswitch
 	$(WW3_BINDIR)/w3_make ww3_grid
 	$(WW3_BINDIR)/w3_make ww3_outf
 	$(WW3_BINDIR)/w3_make ww3_outp
-	@echo "$(SWITCHES)" > $(WW3_BINDIR)/tempswitch
-	@sed -e "s/DIST/SHRD/g"\
-             -e "s/MPIT/ /g"\
-             -e "s/MPI/ /g"\
-             -e "s/PDLIB/ /g"\
-             -e "s/NOGRB/NCEP2 NCO/g"\
-                  $(WW3_BINDIR)/tempswitch > $(WW3_BINDIR)/switch
-	\rm -f $(WW3_BINDIR)/tempswitch
-	$(WW3_BINDIR)/w3_make ww3_outp
-	$(WW3_BINDIR)/w3_make ww3_grib
+	$(WW3_BINDIR)/w3_make ww3_prep
+	$(WW3_BINDIR)/w3_make ww3_gint
+	$(WW3_BINDIR)/w3_make ww3_prnc
+	$(WW3_BINDIR)/w3_make ww3_ounf
+	$(WW3_BINDIR)/w3_make ww3_ounp
+	\mkdir -p $(COMP_BINDIR)
+	\cp -f $(WW3_EXEDIR)/ww3_* $(COMP_BINDIR)/
 
 # ------------------------------------------------------------------------------
-
-
